spring:
  application:
    name: product-service
server:
  port: 8081

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

---
spring:
  profiles: dev
  application:
    name: product-service-dev
server:
  port: 9090

---
spring:
  profiles: prod
  application:
    name: product-service-prod
server:
  port: 4431